[2020-04-18 14:05:15,319 - D:\PyCharm\workspace\com.manage.system\app\auth\views.py  - line:29- INFO]: test登录成功
